<?php

namespace Modules\Core\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JobSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('tref_jobs')->insert([
            ['job' => 'Belum / Tidak Bekerja', 'is_active' => 0],
            ['job' => 'Mengurus Rumah Tangga', 'is_active' => 0],
            ['job' => 'Pelajar / Mahasiswa', 'is_active' => 0],
            ['job' => 'Pensiunan', 'is_active' => 0],
            ['job' => 'Pewagai Negeri', 'is_active' => 1],
            ['job' => 'Tentara Nasional Indonesia', 'is_active' => 0],
            ['job' => 'Kepolisian RI', 'is_active' => 0],
            ['job' => 'Perdagangan', 'is_active' => 0],
            ['job' => 'Petani / Pekebun', 'is_active' => 0],
            ['job' => 'Peternak', 'is_active' => 0],
            ['job' => 'Nelayan / Perikanan', 'is_active' => 0],
            ['job' => 'Industri', 'is_active' => 0],
            ['job' => 'Konstruksi', 'is_active' => 0],
            ['job' => 'Transportasi', 'is_active' => 0],
            ['job' => 'Pegawai Swasta', 'is_active' => 1],
            ['job' => 'Karyawan BUMN', 'is_active' => 0],
            ['job' => 'Karyawan BUMD', 'is_active' => 0],
            ['job' => 'Karyawan Honorer', 'is_active' => 0],
            ['job' => 'Buruh Harian Lepas', 'is_active' => 0],
            ['job' => 'Buruh Tani / Perkebunan', 'is_active' => 0],
            ['job' => 'Buruh Nelayan / Perikanan', 'is_active' => 0],
            ['job' => 'Buruh Peternakan', 'is_active' => 0],
            ['job' => 'Pembantu Rumah Tangga', 'is_active' => 0],
            ['job' => 'Tukang Cukur', 'is_active' => 0],
            ['job' => 'Tukang Listrik', 'is_active' => 0],
            ['job' => 'Tukang Batu', 'is_active' => 0],
            ['job' => 'Tukang Kayu', 'is_active' => 0],
            ['job' => 'Tukang Sol Sepatu', 'is_active' => 0],
            ['job' => 'Tukang Las / Pandai Besi', 'is_active' => 0],
            ['job' => 'Tukang Jahit', 'is_active' => 0],
            ['job' => 'Tukang Gigi', 'is_active' => 0],
            ['job' => 'Penata Rias', 'is_active' => 0],
            ['job' => 'Penata Busana', 'is_active' => 0],
            ['job' => 'Penata Rambut', 'is_active' => 0],
            ['job' => 'Mekanik', 'is_active' => 0],
            ['job' => 'Seniman', 'is_active' => 0],
            ['job' => 'Tabib', 'is_active' => 0],
            ['job' => 'Paraji', 'is_active' => 0],
            ['job' => 'Perancang Busana', 'is_active' => 0],
            ['job' => 'Penerjemah', 'is_active' => 0],
            ['job' => 'Imam Masjid', 'is_active' => 0],
            ['job' => 'Pendeta', 'is_active' => 0],
            ['job' => 'Pastor', 'is_active' => 0],
            ['job' => 'Wartawan', 'is_active' => 0],
            ['job' => 'Ustadz / Mubaligh', 'is_active' => 0],
            ['job' => 'Juru Masak', 'is_active' => 0],
            ['job' => 'Promotor Acara', 'is_active' => 0],
            ['job' => 'Anggota DPR-RI', 'is_active' => 0],
            ['job' => 'Anggota DPD', 'is_active' => 0],
            ['job' => 'Anggota BPK', 'is_active' => 0],
            ['job' => 'Presiden', 'is_active' => 0],
            ['job' => 'Wakil Presiden', 'is_active' => 0],
            ['job' => 'Anggota Mahkamah Konstitusi', 'is_active' => 0],
            ['job' => 'Anggota Kabinet / Kementerian', 'is_active' => 0],
            ['job' => 'Duta Besar', 'is_active' => 0],
            ['job' => 'Gubernur', 'is_active' => 0],
            ['job' => 'Wakil Gubernur', 'is_active' => 0],
            ['job' => 'Bupati', 'is_active' => 0],
            ['job' => 'Wakil Bupati', 'is_active' => 0],
            ['job' => 'Walikota', 'is_active' => 0],
            ['job' => 'Wakil Walikota', 'is_active' => 0],
            ['job' => 'Anggota DPRD Provinsi', 'is_active' => 0],
            ['job' => 'Anggota DPRD Kabupaten / Kota', 'is_active' => 0],
            ['job' => 'Dosen', 'is_active' => 0],
            ['job' => 'Guru', 'is_active' => 0],
            ['job' => 'Pilot', 'is_active' => 0],
            ['job' => 'Pengacara', 'is_active' => 0],
            ['job' => 'Notaris', 'is_active' => 0],
            ['job' => 'Arsitek', 'is_active' => 0],
            ['job' => 'Akuntan', 'is_active' => 0],
            ['job' => 'Konsultan', 'is_active' => 0],
            ['job' => 'Dokter', 'is_active' => 0],
            ['job' => 'Bidan', 'is_active' => 0],
            ['job' => 'Perawat', 'is_active' => 0],
            ['job' => 'Apoteker', 'is_active' => 0],
            ['job' => 'Psikiater / Psikolog', 'is_active' => 0],
            ['job' => 'Penyiar Televisi', 'is_active' => 0],
            ['job' => 'Penyiar Radio', 'is_active' => 0],
            ['job' => 'Pelaut', 'is_active' => 0],
            ['job' => 'Peneliti', 'is_active' => 0],
            ['job' => 'Sopir', 'is_active' => 0],
            ['job' => 'Pialang', 'is_active' => 0],
            ['job' => 'Paranormal', 'is_active' => 0],
            ['job' => 'Pedagang', 'is_active' => 0],
            ['job' => 'Perangkat Desa', 'is_active' => 0],
            ['job' => 'Kepala Desa', 'is_active' => 0],
            ['job' => 'Biarawati', 'is_active' => 0],
            ['job' => 'Wiraswasta', 'is_active' => 1],
            ['job' => 'Ibu Rumah Tangga', 'is_active' => 1]
        ]);
    }
}
